### ISSUE TITLE
後端協助關閉Gaas room

### ISSUE THREAD

**Issue by tom00502** [side-project-at-SPT/split-rails#10]
當前端呼叫關閉房間時
```
/api/v1/rooms/:roomId/close
```
如果房間是由大平台開的，同時通知大平台該game已結束

**Comment by noracami** [comment]
ready to review @tom00502

**Comment by noracami** [comment]
reopen as unimplemented

![image](https://github.com/user-attachments/assets/4927b6a9-b9ac-49fb-ab96-8b3bf62536e4)
