### ISSUE TITLE
大平台結束遊戲API

### ISSUE THREAD

**Issue by tom00502** [side-project-at-SPT/split-rails#6]
# Do this!!
## End of the game

Once the game is over, frontend can call the following endpoint to close the game, and close the iframe window as well.

### request

```
POST 'https://spt-games-split.zeabur.app/api/v1/games/${GAME_ID}/end-game-via-gaas-token'
Headers: 'Authorization: Bearer ${TOKEN_FROM_GAAS}'
```

### response

```json
// 200
{
  "message": "Game ended"
}

// 422
{
  "message": "Failed to end game"
}
```

**Comment by noracami** [comment]
completed

**Comment by noracami** [comment]
Btw (in the future) I'd like to use the GaaS token(Auth0 token) in whole processes.
So that client don't need to keep 2 jwt at the same time 🤣
